# Generated by Django 5.2.3 on 2025-12-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
